import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "DiviSwap Docs | User Guide",
  description: "A step-by-step guide on how to use DiviSwap for swapping tokens and providing liquidity.",
}

export default function DocsUserGuidePage() {
  return (
    <div className="space-y-8">
      <header className="space-y-2">
        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">User Guide</h1>
        <p className="text-xl text-muted-foreground">Your step-by-step guide to navigating the DiviSwap platform.</p>
      </header>

      <section>
        <h2>1. Connecting Your Wallet</h2>
        <p>
          Before you can interact with DiviSwap, you need to connect a Web3 wallet. We support popular wallets like
          MetaMask, Trust Wallet, and others via WalletConnect.
        </p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>Click the "Connect Wallet" button in the top-right corner of the navigation bar.</li>
          <li>Select your preferred wallet from the list.</li>
          <li>Follow the prompts in your wallet to approve the connection to DiviSwap.</li>
          <li>
            Ensure your wallet is set to the Chiliz Chain network. If not, the application will prompt you to switch
            networks.
          </li>
        </ol>
      </section>

      <section>
        <h2>2. Swapping Tokens</h2>
        <p>Swapping tokens on DiviSwap is simple and intuitive.</p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>
            Navigate to the <Link href="/swap">Swap</Link> page.
          </li>
          <li>In the "You Pay" field, select the token you want to sell and enter the amount.</li>
          <li>
            In the "You Receive" field, select the token you want to buy. The estimated amount will be calculated
            automatically.
          </li>
          <li>Review the transaction details, including the price impact and liquidity provider fee.</li>
          <li>Click "Swap". You will be asked to approve the token spending first if you haven't already.</li>
          <li>
            Confirm the transaction in your wallet. Once confirmed on the blockchain, your new tokens will appear in
            your wallet.
          </li>
        </ol>
      </section>

      <section>
        <h2>3. Providing Liquidity</h2>
        <p>By providing liquidity, you can earn a share of the trading fees generated by the protocol.</p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>
            Navigate to the <Link href="/pool">Pool</Link> page.
          </li>
          <li>Click "Add Liquidity".</li>
          <li>Select the pair of tokens you wish to provide. You must provide an equal value of both tokens.</li>
          <li>Enter the amount for one of the tokens, and the other will be calculated automatically.</li>
          <li>Approve spending for both tokens if prompted.</li>
          <li>Click "Supply" and confirm the transaction in your wallet.</li>
          <li>You will receive LP (Liquidity Provider) tokens in your wallet, representing your share of the pool.</li>
        </ol>
      </section>

      <section>
        <h2>4. Removing Liquidity</h2>
        <p>You can remove your liquidity and reclaim your underlying tokens at any time.</p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>
            On the <Link href="/pool">Pool</Link> page, you will see your existing liquidity positions.
          </li>
          <li>Click on the position you wish to remove from.</li>
          <li>Select the percentage of your liquidity you want to remove (from 25% to 100%).</li>
          <li>Click "Remove", review the details, and confirm the transaction in your wallet.</li>
          <li>Your LP tokens will be burned, and the underlying tokens will be returned to your wallet.</li>
        </ol>
      </section>
    </div>
  )
}
